packages:
  - packages/*
  - playgrounds/*

catalogs:
  build:
    tsdown: ^0.23.0
  hooks:
    '@commitlint/cli': ^21.2.2
    '@commitlint/config-conventional': ^21.2.2
    lint-staged: ^17.5.1
    simple-git-hooks: ^2.14.0
  lint:
    '@rhapsodic/eslint-config': ^5.0.0
    eslint: ^10.10.0
  release:
    bumpp: ^12.3.0
  test:
    '@vitest/coverage-v8': ^5.0.0
    tinybench: 6.2.0
    vitest: ^5.0.0
  types:
    typescript: ~6.0.3
  vue:
    '@vitejs/plugin-vue': ^6.0.8
    vite: ^8.3.0
    vue: ^3.5.42
    vue-tsc: ^3.3.11

allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
