import {
  cpSync,
  existsSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';

const r = (path: string) => fileURLToPath(new URL(path, import.meta.url));

const SKILLS_DIR = r('./skills');

if (!existsSync(SKILLS_DIR)) {
  throw new Error(`Missing skills directory: ${SKILLS_DIR}`);
}

const SKILLS_COPY_DIR = r('../../skills');

rmSync(SKILLS_COPY_DIR, { recursive: true, force: true });
cpSync(SKILLS_DIR, SKILLS_COPY_DIR, { recursive: true, force: true });
writeFileSync(
  r('../../skills/README.md'),
  'Skills are generated by the `build.ts` script in the `packages/skills` folder. DO NOT manually edit the skills files.\n',
);

console.log(`Copied skills to: ${SKILLS_COPY_DIR}`);
